export const SET_USER = "SET_USER";
export const SET_LOADING_STATUS = "SET_LOADING_STATUS";
export const GET_ARTICLES = "GET_ARTICLES";
export const GET_RENTALS = "GET_RENTALS";
export const GET_ROOMMATES = "GET_ROOMMATES";
export const SET_OTHER_USER = "SET_OTHER_USER";